### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hayleox** [K8TIY/NASummaries#2]
Hey, just wondering: what is the license for reusing your summaries? I'm working on curating No Agenda stuff on Wikimedia Commons, and I'd really like to utilize your summaries to be able to better categorize each episode.

**Comment by K8TIY** [comment]
Public domain. Thanks for raising the issue! I feel a fool for not addressing this. I'll make sure to slap some boilerplate on the title/home page next time I generate the summaries. Thanks!

**Comment by K8TIY** [comment]
Please note I have made a number of changes to the files and site, to reflect licensing. So I'm going to close the issue for now. Please let me know when your Wikimedia work goes live, I am sure it will be a useful resource.
